config/routes.rb
Rails.application.routes.draw do
  resources :checks

  root "checks#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  default_scope { order(date: :desc) }

  def pretty_amount
    return (amount.to_f.round(2) * 100).to_words(remove_hyphen: true).split.map(&:capitalize).join(" ") + " Cents" if amount < 1
    return amount.to_i.to_words(remove_hyphen: true).split.map(&:capitalize).join(" ") + " Dollars Exactly" if amount.round(2) == amount.to_i
    cents = (amount.round(2) - amount.floor).to_f * 100
    amount.floor.to_words(remove_hyphen: true).split.map(&:capitalize).join(" ") + " Dollars and " + cents.floor.to_words(remove_hyphen: true).split.map(&:capitalize).join(" ") + " Cents"
  end

  def decimal_amount
    "$#{number_with_precision(amount, precision: 2, delimiter: ",")}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: [:show]

  # GET /checks
  # GET /checks.json
  def index
    if params[:query].present?
      @checks = Check.where("lower(#{Check.table_name}.name) LIKE lower(?)", "%#{params[:query]}%")
    else
      @checks = Check.all
    end
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
  end

  # GET /checks/new
  def new
    @check = Check.new
  end

  # GET /checks/1/edit
  # def edit
  # end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new({
      name: check_params[:name],
      amount: check_params[:amount].to_f,
      date: Chronic.parse(check_params[:date]).to_date
    })

    respond_to do |format|
      if @check.save
        format.html { redirect_to @check, notice: 'Check was successfully created.' }
        format.json { render :show, status: :created, location: @check }
      else
        format.html { render :new }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1
  # PATCH/PUT /checks/1.json
  # def update
  #   respond_to do |format|
  #     if @check.update(check_params)
  #       format.html { redirect_to @check, notice: 'Check was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @check }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @check.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /checks/1
  # DELETE /checks/1.json
  # def destroy
  #   @check.destroy
  #   respond_to do |format|
  #     format.html { redirect_to checks_url, notice: 'Check was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check
      @check = Check.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_params
      params.fetch(:check, {}).permit(:name, :amount, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= form_with(model: check, local: true) do |form| %>
  <% if check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(check.errors.count, "error") %> prohibited this check from being saved:</h2>

      <ul>
      <% check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing Check</h1>

<%= render 'form', check: @check %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<%= render partial: 'layouts/navbar', locals: {nav: 'List'} %>
<%= render partial: 'layouts/alerts' %>

<div class="d-flex justify-content-center">
  <div style="width: 90%; max-width: 40rem; margin-top: 6rem"">
    <h5 class="card-title">Check List</h5>
    <% if @checks.empty? %>
      <p>Oh oh. No checks.</p>
    <% else %>
      <div class="list-group">
        <% @checks.each do |check| %>
          <%= link_to check, class:"list-group-item list-group-item-action d-flex justify-content-between align-items-center" do %>

            <div>
              <span><%= check.date.strftime('%Y-%m-%d') %></span>
              <span>&nbsp;&nbsp;<strong><%= check.name %></strong></span>
            </div>


            <div><%= check.decimal_amount %></div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/checks/new.html.erb
<%= render partial: 'layouts/navbar', locals: {nav: 'Home'} %>
<%= render partial: 'layouts/alerts' %>

<div class="d-flex justify-content-center">
  <div class="card" style="width: 90%; max-width: 40rem; margin-top: 6rem"">
    <div class="card-body">
      <h4 class="card-title">Create New Check</h4>
      <%= form_for @check, url: checks_path, class: 'needs-validation' do |f| %>
        <div class="form-group">
          <%= f.label :name %><br />
          <%= f.text_field :name, class: 'form-control', placeholder: 'John Doe', required: true %>
          <div class="invalid-tooltip">
            Name required
          </div>
        </div>
        <div class="form-group">
          <%= f.label :amount %><br />
          <%= f.number_field :amount, class: 'form-control currency', required: true, step: ".01", placeholder: '0.00' %>
          <div class="invalid-tooltip">
            Amount must be greater than 0
          </div>
        </div>
        <div class="form-group">
            <%= f.label :date %><br />
            <%= f.text_field :date, class: 'form-control', data: {provide: 'datepicker', 'auto-close': true, startDate:'05-16-2019'}, placeholder: 'MM-DD-YYYY', required: true %>
            <div class="invalid-tooltip">
              Date required
            </div>
        </div>
        <div class="d-flex flex-row align-items-center mt-2">
          <%= f.submit "Submit", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/checks/show.html.erb
<%= render partial: 'layouts/navbar', locals: {nav: "Home"} %>
<%= render partial: 'layouts/alerts' %>

<div class="d-flex justify-content-center">
  <div style="width: 90%; max-width: 50rem; margin-top: 6rem; padding: 1rem; background-color: #ccc">
    <div style="width: 100%; padding-top: 40%; border: 2px solid black; background-color: inherit; position: relative">
      <h4 style="position: absolute; top: 15%; left: 8%; right: 35%; border-bottom: 1px solid black"><%= @check.name %></h4>
      <p style="position: absolute; top: 15%; left: 70%; right: 8%; border-bottom: 1px solid black"><%= @check.date.strftime('%A, %b %d') %></p>
      <h5 style="position: absolute; top: 45%; left: 10%; right: 20%; border-bottom: 1px solid black"><%= @check.pretty_amount %></h5>
      <div style="position: absolute; top: 80%; left: 50%; right: 8%; border-bottom: 1px solid black"></div>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<% if notice %>
<div id="notice" class="alert alert-info" role="alert">
  <%= notice %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<% nav ||= 'Home' %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">EmpireOne</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if nav=='Home' %>">
        <%= link_to "Write Check", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if nav=='List' %>">
        <%= link_to "List Checks", checks_path, class: 'nav-link' %>
      </li>
    </ul>
    <% if nav=="List" %>
      <%= form_with url: checks_path, class: 'form-inline my-2 my-lg-0', local: true, method: :get do |f| %>
          <%= f.text_field :query, class: 'form-control mr-sm-2', placeholder: 'Search' %>
          <%= f.submit "Search Checks", class: 'btn btn-outline-success my-2 my-sm-0', name: nil %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckWriter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= yield %>

  </body>
</html>